name: Create Public Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: true
        default: '1.0.0'
      description:
        description: '发布说明'
        required: false
        default: 'New Release'
        
permissions:
  contents: write
  pages: write
  id-token: write        

jobs:
  build:
    strategy:
      matrix:
        node-version: [20, 22]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: 构建JSC文件
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          npm install
          npm run build
          node genJsc.js 
          
      - name: 上传JSC文件
        uses: actions/upload-artifact@v3
        with:
          name: jsc-files-${{ matrix.os }}
          path: dist/Test_*.jsc
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: 下载所有JSC文件
        uses: actions/download-artifact@v3
        with:
          path: jsc
          
      - name: 生成发布包
        run: |
          mkdir dist
          mv jsc/**/Test_*.jsc dist/
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          npm install
          npm run bp
          # 准备Pages目录
          mkdir -p pages
          mv test-${{ github.event.inputs.version }}.tgz pages/

      - name: 上传到 GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./pages
          
      - name: 部署 GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 输出下载地址
        run: |
          echo "包下载地址: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/test-${{ github.event.inputs.version }}.tgz"    
