name: Create Public Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: true
        default: '1.0.0'
      description:
        description: '发布说明'
        required: false
        default: 'New Release'
        
permissions:
  contents: write        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          
      - name: 更新版本号 安装依赖 生成npm包
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          npm i bytenode -g
          npm install
          npm run bp
        
      - name: 上传Release
        uses: softprops/action-gh-release@v1
        with:
          files: test-${{ github.event.inputs.version }}.tgz
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          generate_release_notes: false
