name: Create Public Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: true
        default: '1.0.0'
      description:
        description: '发布说明'
        required: false
        default: 'New Release'
        
permissions:
  contents: write        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          
      - name: 更新版本号 安装依赖 生成npm包
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          npm install
          npm run bp
        
      - name: 创建Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          draft: true           # 设置为草稿模式
          prerelease: false

      - name: 上传Release资源
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test-${{ github.event.inputs.version }}.tgz
          asset_name: test-${{ github.event.inputs.version }}.tgz
          asset_content_type: application/gzip

      - name: 发布Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
